#!/usr/bin/env bash

pushd ~/dotfiles >/dev/null

# zsh
# echo 'installing zsh configuration...'
# if [[ -f "$HOME/.zshrc" ]]; then
# 	echo '- backing up existing .zshrc...'
# 	mv ~/.zshrc ~/.zshrc-backup
# fi
# if [[ -f "$HOME/.zshenv" ]]; then
# 	echo '- backing up existing .zshenv...'
# 	mv ~/.zshenv ~/.zshenv-backup
# fi
# ln -sf ~/dotfiles/zsh/.zshrc ~/.zshrc
# ln -sf ~/dotfiles/zsh/.zshenv ~/.zshenv
ln -sf ~/dotfiles/zsh/.zsh_favlist ~/.zsh_favlist
# vim
echo 'installing vim configuration...'
mkdir -p ~/.config/nvim

ln -sf ~/dotfiles/vim/colors.vim ~/.config/nvim/colors.vim
ln -sf ~/dotfiles/vim/colors ~/.config/nvim/colors
ln -sf ~/dotfiles/vim/commands.vim ~/.config/nvim/commands.vim
ln -sf ~/dotfiles/vim/events.vim ~/.config/nvim/events.vim
ln -sf ~/dotfiles/vim/functions.vim ~/.config/nvim/functions.vim
ln -sf ~/dotfiles/vim/init.vim ~/.config/nvim/init.vim
ln -sf ~/dotfiles/vim/keymaps.vim ~/.config/nvim/keymaps.vim
ln -sf ~/dotfiles/vim/plugins.vim ~/.config/nvim/plugins.vim
ln -sf ~/dotfiles/vim/settings.vim ~/.config/nvim/settings.vim

# tmux
echo 'installing tmux configuration...'
ln -sf ~/dotfiles/tmux/.tmux.conf ~/.tmux.conf
ln -sf ~/dotfiles/tmux/.tmux-osx.conf ~/.tmux-osx.conf

# tmuxifier
echo 'installing tmuxifier configuration...'
if [[ -d "$HOME/.tmuxifier" ]]; then
	mkdir -p ~/.tmuxifier/layouts
	pushd ~/.tmuxifier/layouts >/dev/null
	for layout in ~/dotfiles/tmuxifier/layouts/*; do
		ln -sf $layout
	done
	popd >/dev/null
else
	echo 'tmuxifier is not installed, skipping'
fi

# ctags
echo 'installing ctags configuration...'
ln -sf ~/dotfiles/ctags/.ctags ~/.ctags

# alacritty
echo 'installing alacritty configuration...'
mkdir -p ~/.config
ln -sf ~/dotfiles/alacritty/alacritty.yml ~/.config/alacritty.yml

popd >/dev/null

exit 0
