;;;  -*- lexical-binding: t; -*-

;; (require 'doom-themes)
;; (load-theme 'doom-challenger-deep t)
;; (load-theme 'doom-acario-dark t) ;;an original dark theme (thanks to gagbo)
;; (load-theme 'doom-acario-light t) ;;an original light theme (thanks to gagbo)
;; (load-theme 'doom-city-lights t) ;;based on Atom's City lights (thanks to fuxialexander)
;; (load-theme 'doom-challenger-deep t) ;;based on Vim's Challenger deep theme (thanks to fuxialexander)
;; (load-theme 'doom-dark+ ported from VS Code's Dark+ theme (thanks to ema2159)
;; (load-theme 'doom-dracula t) ;;an implementation of Dracula theme (thanks to fuxialexander)
;; (load-theme 'doom-ephemeral t) ;;inspired in the Ephemeral Theme from elenapan's dotfiles (thanks to karetsu)
;; (load-theme 'doom-fairy-floss t) ;;a candy colored Sublime theme by sailorhg (thanks to ema2159)
;; (load-theme 'doom-gruvbox t) ;;adapted from Morhetz's Gruvbox (thanks to JongW)
;; (load-theme 'doom-horizon t) ;;ported from VS Code's Horizon (thanks to karetsu)
;; (load-theme 'doom-Iosvkem t) ;;adapted from Iosvkem (thanks to neutaaaaan)
;; (load-theme 'doom-laserwave t) ;;a clean 80's synthwave / outrun theme inspired by VS Code's laserwave (thanks to hyakt)
;; (load-theme 'doom-material t) ;; adapted from Material Themes (thanks to tam5)
;; (load-theme 'doom-manegarm t) ;;an original autumn-inspired dark theme (thanks to kenranunderscore)
;; (load-theme 'doom-molokai t) ;;a theme based on Texmate's Monokai
;; (load-theme 'doom-monokai-classic t) ;;port of Monokai's Classic variant (thanks to ema2159)
;; (load-theme 'doom-monokai-pro t) ;;port of Monokai's Pro variant (thanks to kadenbarlow)
;; (load-theme 'doom-moonlight t) ;;ported from VS Code's Moonlight Theme (thanks to Brettm12345)
;; (load-theme 'doom-nord t) ;;dark variant of Nord (thanks to fuxialexander)
;; (load-theme 'doom-nord-light t) ;;light variant of Nord (thanks to fuxialexander)
;; (load-theme 'doom-nova t) ;;adapted from Nova (thanks to bigardone)
;; (load-theme 'doom-oceanic-next t) ;;adapted from Oceanic Next theme (thanks to juanwolf)
;; (load-theme 'doom-opera t) ;;an original dark theme (thanks to jwintz)
;; (load-theme 'doom-opera-light t) ;;an original light theme (thanks to jwintz)
;; (load-theme 'doom-outrun-electric t) ;;a neon colored theme inspired in VS Code's Outrun Electric (thanks to ema2159)
;; (load-theme 'doom-palenight t) ;;adapted from Material Themes (thanks to Brettm12345)
;; (load-theme 'doom-peacock t) ;;based on Peacock from daylerees' themes (thanks to teesloane)
;; (load-theme 'doom-rouge t) ;;ported from VSCode's Rouge Theme (thanks to JordanFaust)
;; (load-theme 'doom-snazzy t) ;;a dark theme inspired in Atom's Hyper Snazzy (thanks to ar1a)
;; (load-theme 'doom-solarized-dark t) ;;dark variant of Solarized (thanks to ema2159)
;; (load-theme 'doom-solarized-light t) ;;light variant of Solarized (thanks to fuxialexander)
;; (load-theme 'doom-sourcerer t) ;;based on Sourcerer (thanks to defphil)
(load-theme 'doom-spacegrey t) ;;I'm sure you've heard of it (thanks to teesloane)
;; (load-theme 'doom-tomorrow-day t) ;;Tomorrow's light variant (thanks to emacswatcher)
;; (load-theme 'doom-tomorrow-night t) ;;one of the dark variants of Tomorrow (thanks to emacswatcher)
;; (load-theme 'doom-wilmersdorf t) ;;port of Ian Pan's Wilmersdorf (thanks to ema2159)

(setq doom-font (font-spec :family "PragmataPro Liga 1.1" :size 23))
;; (setq doom-font (font-spec :family "SF Mono" :size 19))
(setq doom-variable-pitch-font (font-spec :family "SF Pro Display" :size 17))
;; (setq doom-variable-pitch-font (font-spec :family "Roboto" :size 15))
;; (setq doom-font (font-spec :family "Monoid" :size 19))
(custom-set-faces!
  `(font-lock-type-face :weight bold)
  `(font-lock-function-name-face :weight bold)
  `(font-lock-string-face :background ,(doom-lighten 'bg 0.05))
  )

(custom-theme-set-faces! 'doom-spacegrey
  `(font-lock-keyword-face :weight bold :foreground ,(doom-color 'blue))
  `(font-lock-constant-face :weight bold :foreground ,(doom-lighten (doom-color 'blue) 0.4))
  `(font-lock-preprocessor-face :foreground ,(doom-blend (doom-color 'cyan) (doom-color 'grey) 0.8))
  `(font-lock-string-face :foreground ,(doom-lighten (doom-color 'blue) 0.3))
  `(font-lock-type-face :foreground ,(doom-blend (doom-color 'yellow) (doom-color 'grey) 0.7))
  `(font-lock-function-name-face :foreground ,(doom-color 'green))
 )

;; (after! company
;;   (custom-set-faces!
;;     `(company-tooltip-selection :foreground ,(doom-color 'black))
;;     `(company-tooltip-common :foreground ,(doom-color 'black))
;;     `(company-tooltip-annotation :foreground ,(doom-color 'grey))
;;     )
;;   )

(after! haskell
  (custom-set-faces!
    `(haskell-keyword-face :foreground "coral")
    `(haskell-pragma-face :foreground ,(doom-color 'red))
    `(haskell-pragma-face :foreground ,(doom-darken 'bg 0.5))
    `(haskell-operator-face :foreground ,(doom-color 'orange))
    `(haskell-definition-face :foreground ,(doom-color 'blue))
    `(haskell-quasi-quote-face :foreground ,(doom-color 'magenta))
    `(haskell-type-face :weight bold)
    `(haskell-definition-face :weight bold)
    )
  )

(after! hl-todo
  (setq hl-todo-keyword-faces
        `(("TODO"  . ,(face-foreground 'warning))
          ("FIXME" . ,(face-foreground 'error))
          ("XXX" . ,(face-foreground 'error))
          ("NOTE"  . ,(face-foreground 'success))))
  )

(after! treemacs
  (custom-set-faces!
    `(treemacs-root-face :height 1.3 :weight bold :slant normal :family "SF Pro Display" :background ,(doom-color 'bg))
    `(treemacs-directory-collapsed-face :height 0.9 :weight normal :slant normal :family "SF Pro Display")
    `(treemacs-directory-face :height 0.9 :weight normal :slant normal :family "SF Pro Display")
    `(treemacs-file-face :height 0.9 :weight normal :slant normal :family "SF Pro Display")
    `(treemacs-fringe-indicator-face :height 0.9 :weight normal :slant normal :family "SF Pro Display")
    `(treemacs-git-added-face :height 0.9 :weight normal :slant normal :family "SF Pro Display")
    `(treemacs-git-conflict-face :height 0.9 :weight normal :slant normal :family "SF Pro Display")
    `(treemacs-git-ignored-face :height 0.9 :weight normal :slant normal :family "SF Pro Display")
    `(treemacs-git-modified-face :height 0.9 :weight normal :slant normal :family "SF Pro Display")
    `(treemacs-git-renamed-face :height 0.9 :weight normal :slant normal :family "SF Pro Display")
    `(treemacs-git-unmodified-face :height 0.9 :weight normal :slant normal :family "SF Pro Display")
    `(treemacs-git-untracked-face :height 0.9 :weight normal :slant normal :family "SF Pro Display")
    `(treemacs-help-column-face :height 0.9 :weight normal :slant normal :family "SF Pro Display")
    `(treemacs-help-title-face :height 0.9 :weight normal :slant normal :family "SF Pro Display")
    `(treemacs-on-failure-pulse-face :height 0.9 :weight normal :slant normal :family "SF Pro Display")
    `(treemacs-on-success-pulse-face :height 0.9 :weight normal :slant normal :family "SF Pro Display")
    `(treemacs-tags-face :height 0.9 :weight normal :slant normal :family "SF Pro Display")
    `(treemacs-term-node-face :height 0.9 :weight normal :slant normal :family "SF Pro Display")
    )
  )

;;; rust
(after! rustic
  (custom-set-faces!
    `(rustic-string-interpolation-face :slant normal)
    `(rustic-string-interpolation-face :foreground ,(doom-lighten (doom-color 'magenta) 0.1)
                                       :background ,(doom-lighten 'bg 0.07))
    )
  )
