;;;  -*- no-byte-compile: t; -*-

(package! yasnippet)
(package! doom-modeline)
(package! exec-path-from-shell)
(package! prettier-js)
(package! evil-leader)
(package! evil-nerd-commenter)
(package! hindent)
(package! transpose-frame)
(package! nginx-mode)
(package! default-text-scale)
;; (package! gruvbox-theme)
(package! darktooth-theme)
(package! base16-theme)
(package! hemisu-theme)
(package! mustache-mode)
(package! golden-ratio)
(package! lsp-mode)
(package! lsp-ui)
(package! company-lsp)
(package! company-go)
(package! vmd-mode)
(package! evil-terminal-cursor-changer)
(package! highlight-indent-guides)
(package! ormolu :recipe (:host github :repo "vyorkin/ormolu.el"))
(package! fzf)
(package! dhall-mode)
(package! manage-minor-mode)
(package! toml-mode)
(package! company-nginx)
(package! lsp-haskell)
(package! hlint-refactor)
