export ZSH=$HOME/.oh-my-zsh
# export UPDATE_ZSH_DAYS=13
export LANG=en_US.UTF-8
export P4CONFIG=.p4config
export P4USER=sawyer
export P4IGNORE=.p4ignore
export P4DIFF=/usr/local/bin/ksdiff
export P4MERGE=/usr/local/bin/ksdiff
export P4TICKETS=$HOME/.p4tickets
export GOPATH=~/gocode
export EDITOR=nvim
export LESS="-X -R -i"
XDG_CONFIG_HOME=/Users/sawyer/.config
XDG_DATA_HOME=/Users/sawyer/.local/share
export FZF_DEFAULT_COMMAND='ag -g ""'
export PATH=$HOME/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:$HOME/.nvm/versions/node/v6.12.0/bin
