export ZSH=$HOME/.oh-my-zsh
# export UPDATE_ZSH_DAYS=13
export LANG=en_US.UTF-8
export P4CONFIG=.p4config
export P4USER=sawyer
export P4IGNORE=.p4ignore
export P4TICKETS=$HOME/.p4tickets
# em is a small zsh script to launch emacs smarter - if the daemon is running, attach to it; if not, start it
export EDITOR='emacs -nw'
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export FZF_DEFAULT_COMMAND='ag -g ""'
export PATH=node_modules/.bin
export PATH=$PATH:$HOME/.nvm/versions/node/v8.11.3/bin
export PATH=$PATH:$HOME/.cargo/bin
export PATH=$PATH:$HOME/.fzf/bin
export PATH=$PATH:$HOME/.local/bin
export PATH=$PATH:$HOME/.cabal/bin
export PATH=$PATH:/usr/local/bin
export PATH=$PATH:/usr/local/sbin
export PATH=$PATH:/usr/bin
export PATH=$PATH:/bin
export PATH=$PATH:/usr/sbin
export PATH=$PATH:/sbin
export GOPATH=~/gocode
export TERM=xterm-256color
export LESS='-F -g -i -M -r -w -X -z-4'
